name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build & Publish
        run: npx electron-builder --publish never
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false # Disable mac signing if you don’t have certs

      - name: Create GitHub Release (optional if not using auto-publish)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: Pixel Climber ${{ github.ref_name }}
          files: dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
